# For more info on HTTP files go to https://aka.ms/vs/httpfile

GET http://localhost:8080/todo-list

### Add item
POST http://localhost:8080/todo-list
Content-Type: application/json

{
  "description": "Close Garage"
}

### Change Status
POST http://localhost:8080/todo-list-status-change
Content-Type: application/json

{
  "id": "6d9c89c0-d615-4fd5-b671-43cf7bc40df2",
  "description": "Mow Lawn",
  "status": "Waiting"
}